# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account_number', models.BigIntegerField()),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=150)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finance.Account')),
            ],
            options={
                'db_table': 'charges',
            },
        ),
    ]
