# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20161117_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='charge',
            name='purpose',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
